version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ms-contract-db
    environment:
      POSTGRES_DB: ms-contract-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


